"""Initial migration.

Revision ID: 5e1d8ed7badf
Revises: 
Create Date: 2023-11-03 21:26:41.833855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1d8ed7badf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('authors_name_key', type_='unique')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_isbn_key', type_='unique')
        batch_op.drop_constraint('books_title_key', type_='unique')

    with op.batch_alter_table('books_authors', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    with op.batch_alter_table('books_categories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    with op.batch_alter_table('books_publishers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'publishers', ['publisher_id'], ['id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_name_key', type_='unique')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_constraint('publishers_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_unique_constraint('publishers_name_key', ['name'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('categories_name_key', ['name'])

    with op.batch_alter_table('books_publishers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('books_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('books_authors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_unique_constraint('books_title_key', ['title'])
        batch_op.create_unique_constraint('books_isbn_key', ['isbn'])

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_unique_constraint('authors_name_key', ['name'])

    # ### end Alembic commands ###
